api_key: sk-f932d2a6894c46b7a46855378127040c
models:
  source_risk:
    base_url: https://api.deepseek.com
    model: deepseek-chat
    temperature: 0.2
    max_tokens: 450
    timeout: 60
    prompt_file: ../rules/source_risk.yml
    parallel_workers: 1
    
  sink_vuln:
    base_url: https://api.deepseek.com
    model: deepseek-chat
    temperature: 0.2
    max_tokens: 2200
    timeout: 120
    prompt_file: ../rules/sink_vuln.yml
    parallel_workers: 1
